routes/web.php
<?php

Route::get('login', 'Auth\LoginController@getLogin')->name('login');
Route::post('admin', 'Auth\LoginController@postLogin')->name('login.post');

Route::get('/', 'HomeController@index')->name('site.inicio');

Route::get('liturgia/{dia}/{mes}/{ano}', 'lirtugiaController@index')->name('api.liturgia');

Route::get('liturgia-diaria/{dia}/{mes}/{ano}', 'lirtugiaController@lirtugiaPage')->name('site.lirtugia');

Route::get('pedido-oracao', 'PedidoOracaoController@create')->name('pedido.oracao.index');
Route::post('pedido-oracao', 'PedidoOracaoController@store')->name('pedido.oracao.store');

Route::get('velas', 'PedidoOracaoController@acendaVela')->name('pedido.velas.index');
Route::post('velas', 'PedidoOracaoController@storeVela')->name('pedido.velas.store');


Route::get('pagina/{titulo}/{id}', 'PaginaController@show')->name('site.pagina.show')->where("id", "[0-9]+");

Route::get('noticia/{titulo}/{id}', 'PaginaController@show')->name('site.noticia.show')->where("id", "[0-9]+");

Route::get('noticias', 'NoticiaController@getAllNoticias')->name('site.noticia.all');

Route::get('artigos', 'NoticiaController@getAllArtigos')->name('site.artigo.all');

Route::get('oracoes', 'NoticiaController@getAllOracoes')->name('site.oracao.all');

Route::get('galerias-fotos', 'GaleriaController@getAllGalerias')->name('site.galerias.all');

Route::get('comunidades', 'PaginaController@getAllComunidades')->name('site.comunidade.all');

Route::get('galeria-fotos/{titulo}/{id}', 'GaleriaController@getShow')->name('site.galeria.show');


/**
 * ADMINISTRATIVO
 */
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function() {

	Route::get('deslogar', 'Auth\LoginController@logout')->name('login.deslogar');

	/** Categorias **/
	Route::resource('categorias', 'CategoriaController');

	/** Noticias **/
	Route::resource('noticias', 'NoticiaController');

	/** Paginas **/
	Route::resource('paginas', 'PaginaController');

	/** Galeria **/
	Route::resource('galerias', 'GaleriaController');

	/*** Lirtugia *****/
	Route::resource('lirtugia', 'lirtugiaController');

	Route::get('fotos/{id}', 'GaleriaController@getFotos')->name('fotos.index');
	Route::post('fotos/{id}', 'GaleriaController@postFotos')->name('fotos.store');
	Route::delete('fotos/{id}', 'GaleriaController@deleteFoto')->name('fotos.delete');

	/** Pedidos Oração **/
	Route::resource('pedidos-oracao', 'PedidoOracaoController');

	Route::resource('usuarios', 'UsuarioController');

	Route::get('velas','PedidoOracaoController@getAllVelasAdmin')->name('admin.velas.index');
	Route::get('velas/{id}','PedidoOracaoController@getShowVelasAdmin')->name('admin.velas.show');
	Route::get('velas/{status}/{id}','PedidoOracaoController@getMudarStatus')->name('admin.velas.status');
	Route::delete('velas/{id}','PedidoOracaoController@velaDestroy')->name('admin.velas.destroy');

	Route::get('/', function () {
	    return view('admin/pages/index');
	})->name('home');

});
	

app/Models/Categoria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    
	protected $fillable = [ 
		'nome'
	];

}

app/Http/Controllers/CategoriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Categoria;

class CategoriaController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categorias = Categoria::all();
        return view('admin/pages/categorias/list', compact(['categorias']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/pages/categorias/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nome' => 'required|unique:categorias,nome',
        ]);

        if(Categoria::create($request->all())) {
            
            $request->session()->flash('success', 'A Categoria foi adicionada com sucesso');

            return redirect()->route('categorias.index');

        }
        return redirect()->back()
            ->withInput()
            ->withErrors('Erro ao adicionar a categoria!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categoria = Categoria::find($id);
        return view('admin/pages/categorias/edit', compact(['categoria']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nome' => 'required|unique:categorias,nome',
        ]);

        if(Categoria::find($id)->update($request->all())) {            
            $request->session()->flash('success', 'A Categoria foi atualizada com sucesso');
            return redirect()->route('categorias.index');
        }
        return redirect()->back()
            ->withInput()
            ->withErrors('Erro ao atualizar a categoria!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Categoria::find($id)->delete()){
            session()->flash('success', 'A Categoria foi removida com sucesso');
            return redirect()->route('categorias.index');
        }
        return redirect()->back()->withInput()->withErrors('Erro ao remover a categoria!');        
        
    }
}

resources/views/admin/pages/categorias/create.blade.php
@extends('admin.template')

@section('css')

@endsection

@section('title', 'Categoria')
@section('sub-title', 'Nova')

@section('rotas')
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="{{ route('categorias.index') }}"><i class="fa fa-link"></i> Categorias</a></li>
    <li class="active">Nova Categoria</li>
@endsection

@section('conteudo')
<div class="row">
  <div class="col-md-12">
    <div class="box box-info">
      <!-- /.box-header -->
      <div class="box-body pad">
        @include('admin.parts.errors')
        <form action="{{ route('categorias.store') }}"  method="post">
          {{ csrf_field() }}
          <div class="form-group">
            <label>Nome</label>
            <input type="text" name="nome" class="form-control" value="{{ old('nome') }}" placeholder="Nome da categoria">
          </div>

          <div class="form-group">
            <input type="submit" name="cadastrar" value="Cadastrar Categoria" class="btn btn-success">
            <input type="reset" name="limpar" value="Limpar campos" class="btn btn-primary">
            <a href="{{ route('categorias.index') }}" title="Voltar" class="btn btn-default">Voltar</a>
          </div>
        </form>
              
      </div>
    </div>
    <!-- /.box -->
<!-- ./row -->
@endsection


@section('js')
<!-- CK Editor -->
<script src="https://cdn.ckeditor.com/4.5.7/standard/ckeditor.js"></script>

<script>
  $(function () {
    CKEDITOR.replace('editor1');
  });
</script>
@endsection

</body>
</html>

resources/views/admin/pages/categorias/edit.blade.php
@extends('admin.template')

@section('css')

@endsection

@section('title', 'Categoria')
@section('sub-title', 'Atualizar')

@section('rotas')
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="{{ route('categorias.index') }}"><i class="fa fa-link"></i> Categorias</a></li>
    <li class="active">Editar categoria</li>
@endsection

@section('conteudo')
<div class="row">
  <div class="col-md-12">
    <div class="box box-info">
      <!-- /.box-header -->
      <div class="box-body pad">
        @include('admin.parts.errors')
        <form action="{{ route('categorias.update', $categoria->id) }}"  method="post">
          {{ csrf_field() }}
          <input name="_method" type="hidden" value="PUT">
          <div class="form-group">
            <label>Nome</label>
            <input type="text" name="nome" class="form-control" value="{{ $categoria->nome }}" placeholder="Nome da categoria">
          </div>

          <div class="form-group">
            <input type="submit" name="Editar" value="Editar Categoria" class="btn btn-success">
            <a href="{{ route('categorias.destroy', $categoria->id) }}" title="Remover categoria" class="btn btn-danger"  data-method="delete" data-token="{{csrf_token() }}" data-confirm="Are you sure?">Remover Categoria</a>
            
            <a href="{{ route('categorias.index') }}" title="Voltar" class="btn btn-default">Voltar</a>
          </div>
        </form>
              
      </div>
    </div>
    <!-- /.box -->
<!-- ./row -->
@endsection


@section('js')
<!-- CK Editor -->
<script src="https://cdn.ckeditor.com/4.5.7/standard/ckeditor.js"></script>

<script>
  $(function () {
    CKEDITOR.replace('editor1');
  });
</script>
@endsection

</body>
</html>

resources/views/admin/pages/categorias/list.blade.php
@extends('admin.template')

@section('css')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('js/plugins/datatables/dataTables.bootstrap.css') }}">
@endsection

@section('title', 'Categorias')
@section('sub-title', 'Todas')

@section('rotas')
  <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Categorias</li>
@endsection

@section('conteudo')
  <div class="box">
      <div class="box-header">
        <a href="{{ route('categorias.create') }}" class="btn btn-block btn-primary btn-lg">
          Adicionar uma nova categoria
        </a>        
      </div>
      
        <!-- /.box-header -->
        <div class="box-body">
        @include('admin.parts.success')
          <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>#</th>
              <th>Nome</th>
              <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            @foreach($categorias as $c)
            <tr>
              <td>{{ $c->id }}</td>
              <td>{{ $c->nome }}</td>
              <td class="text-center">
                  <a href="{{ route('categorias.edit', $c->id) }}" title="Editar categoria" class="btn-sm btn-primary"><i class="fa fa-edit"></i></a>

                  <a href="{{ route('categorias.destroy', $c->id) }}" title="Remover categoria" class="btn-sm btn-danger"  data-method="delete" data-token="{{csrf_token() }}" data-confirm="Você tem certeza que deseja remover essa categoria ?">

                  <i class="fa fa-remove"></i>

                  </a>
              </td>
            </tr>
            @endforeach
            </tbody>
            <tfoot>
            <tr>
              <th>#</th>
              <th>Nome</th>
              <th>Ações</th>
            </tr>
            </tfoot>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
      <!-- /.row -->
@endsection
      
@section('js')

<!-- DataTables -->
<script src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<!-- SlimScroll -->
<script src="{{ asset('js/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('js/plugins/fastclick/fastclick.js') }}"></script>

<!-- AdminLTE App -->

<script>
  $(function () {
    $("#example1").DataTable( {
      "language" :{
        "sEmptyTable": "Nenhum registro encontrado",
        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
        "sInfoPostFix": "",
        "sInfoThousands": ".",
        "sLengthMenu": "_MENU_ resultados por página",
        "sLoadingRecords": "Carregando...",
        "sProcessing": "Processando...",
        "sZeroRecords": "Nenhum registro encontrado",
        "sSearch": "Pesquisar",
        "oPaginate": {
            "sNext": "Próximo",
            "sPrevious": "Anterior",
            "sFirst": "Primeiro",
            "sLast": "Último"
        },
        "oAria": {
            "sSortAscending": ": Ordenar colunas de forma ascendente",
            "sSortDescending": ": Ordenar colunas de forma descendente"
        }
      },
    });    
  });
</script>

@endsection