routes/web.php
<?php

Route::get('login', 'Auth\LoginController@getLogin')->name('login');
Route::post('admin', 'Auth\LoginController@postLogin')->name('login.post');

Route::get('/', 'HomeController@index')->name('site.inicio');

Route::get('liturgia/{dia}/{mes}/{ano}', 'lirtugiaController@index')->name('api.liturgia');

Route::get('liturgia-diaria/{dia}/{mes}/{ano}', 'lirtugiaController@lirtugiaPage')->name('site.lirtugia');

Route::get('pedido-oracao', 'PedidoOracaoController@create')->name('pedido.oracao.index');
Route::post('pedido-oracao', 'PedidoOracaoController@store')->name('pedido.oracao.store');

Route::get('velas', 'PedidoOracaoController@acendaVela')->name('pedido.velas.index');
Route::post('velas', 'PedidoOracaoController@storeVela')->name('pedido.velas.store');


Route::get('pagina/{titulo}/{id}', 'PaginaController@show')->name('site.pagina.show')->where("id", "[0-9]+");

Route::get('noticia/{titulo}/{id}', 'PaginaController@show')->name('site.noticia.show')->where("id", "[0-9]+");

Route::get('noticias', 'NoticiaController@getAllNoticias')->name('site.noticia.all');

Route::get('artigos', 'NoticiaController@getAllArtigos')->name('site.artigo.all');

Route::get('oracoes', 'NoticiaController@getAllOracoes')->name('site.oracao.all');

Route::get('galerias-fotos', 'GaleriaController@getAllGalerias')->name('site.galerias.all');

Route::get('comunidades', 'PaginaController@getAllComunidades')->name('site.comunidade.all');

Route::get('galeria-fotos/{titulo}/{id}', 'GaleriaController@getShow')->name('site.galeria.show');


/**
 * ADMINISTRATIVO
 */
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function() {

	Route::get('deslogar', 'Auth\LoginController@logout')->name('login.deslogar');

	/** Categorias **/
	Route::resource('categorias', 'CategoriaController');

	/** Noticias **/
	Route::resource('noticias', 'NoticiaController');

	/** Paginas **/
	Route::resource('paginas', 'PaginaController');

	/** Galeria **/
	Route::resource('galerias', 'GaleriaController');

	/*** Lirtugia *****/
	Route::resource('lirtugia', 'lirtugiaController');

	Route::get('fotos/{id}', 'GaleriaController@getFotos')->name('fotos.index');
	Route::post('fotos/{id}', 'GaleriaController@postFotos')->name('fotos.store');
	Route::delete('fotos/{id}', 'GaleriaController@deleteFoto')->name('fotos.delete');

	/** Pedidos Oração **/
	Route::resource('pedidos-oracao', 'PedidoOracaoController');

	Route::resource('usuarios', 'UsuarioController');

	Route::get('velas','PedidoOracaoController@getAllVelasAdmin')->name('admin.velas.index');
	Route::get('velas/{id}','PedidoOracaoController@getShowVelasAdmin')->name('admin.velas.show');
	Route::get('velas/{status}/{id}','PedidoOracaoController@getMudarStatus')->name('admin.velas.status');
	Route::delete('velas/{id}','PedidoOracaoController@velaDestroy')->name('admin.velas.destroy');

	Route::get('/', function () {
	    return view('admin/pages/index');
	})->name('home');

});
	

app/Models/Pagina.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Pagina extends Model
{
    //
}

app/Http/Controllers/PaginaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Categoria;
use App\Models\Noticia;
use Image;

class PaginaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $noticias = Noticia::where('tipo', 2)->get();
        return view('admin/pages/paginas/list', compact('noticias'));
    }

    /** Pagina com todas as comunidades **/
    public function getAllComunidades()
    {
        $comunidades = Noticia::where('tipo', 2)->where('ativo', 1)->where('categoria_id', 2)->paginate(6);
        return view('site.pages.comunidades', compact('comunidades'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categorias = Categoria::whereIn('id', [2,4,3])->get();
        return view('admin/pages/paginas/create', compact(['categorias']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'titulo' => 'required|unique:noticias,titulo',
            'conteudo' => 'required',
            'categoria_id' => 'required',
        ]);

        $request['resumo'] = substr($request->get('conteudo'), 0, strrpos(substr($request->get('conteudo'), 0, 200), ' ')) . '...';
        $request['capa']  = '';
 
        if(Noticia::create($request->all())) {
            $request->session()->flash('success', 'A pagina foi adicionada com sucesso');
            return redirect()->route('paginas.index');
        }

        return redirect()->back()
            ->withInput()
            ->withErrors('Erro ao adicionar a pagina!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($titulo, $id)
    {
        $pagina = Noticia::find($id);
        return view('site.pages.pagina', compact('pagina'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categorias = Categoria::whereIn('id', [2,4,3])->get();
        $noticia = Noticia::find($id);
        return view('admin/pages/paginas/edit', compact('categorias', 'noticia'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'titulo' => 'required',
            'conteudo' => 'required',
            'categoria_id' => 'required',
        ]);

        $request['resumo'] = substr($request->get('conteudo'), 0, strrpos(substr($request->get('conteudo'), 0, 200), ' ')) . '...';

        $noticia = Noticia::find($id);

        if($noticia->update($request->all())) {
            $request->session()->flash('success', 'A pagina foi atualizada com sucesso');
            return redirect()->route('paginas.index');
        }

        return redirect()->back()
            ->withInput()
            ->withErrors('Erro ao atualizar a pagina!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete = Noticia::find($id);        
        if($delete->delete()){
            session()->flash('success', 'A pagina foi removida com sucesso');
            return redirect()->route('paginas.index');
        }
        return redirect()->back()->withInput()->withErrors('Erro ao remover a pagina!');
    }
}

resources/views/admin/pages/paginas/create.blade.php
@extends('admin.template')

@section('css')
  <link rel="stylesheet" href="{{ asset('js/plugins/select2/select2.min.css') }}">
@endsection

@section('title', 'Paginas')
@section('sub-title', 'Nova')

@section('rotas')
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ route('paginas.index') }}"><i class="fa  fa-file-o"></i> Paginas</a></li>
    <li class="active">Nova Pagina</li>
@endsection

@section('conteudo')
<div class="row">
  <div class="col-md-12">
    <div class="box box-info">
    @include('admin.parts.errors')
      <!-- /.box-header -->
      <div class="box-body pad">
        <form action="{{ route('paginas.store') }}" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}
          <div class="form-group">
            <label>Titulo</label>
            <input type="text" class="form-control" name="titulo" placeholder="">
            <input type="hidden" class="form-control" name="tipo" value="2">
            <input type="hidden" class="form-control" name="user_id" value="{{Auth::user()->id }}">
          </div>       
          <div class="form-group">              
            <label>Categoria</label>
            <select name="categoria_id" class="form-control select2" style="width: 100%;">
              <option selected="selected">Selecione a Categoria </option>
              @foreach($categorias as $c)              
                <option value="{{ $c->id }}">{{ $c->nome }}</option>
              @endforeach
            </select>
          </div>

          <div class="form-group">
            <label>Conteudo</label>
            <textarea id="editor1" name="conteudo" rows="10" cols="80"></textarea>
          </div>

          <div class="form-group">              
            <label>Status</label>
            <select name="ativo" class="form-control select2" style="width: 100%;">
              <option value="1" selected="selected">Publicar</option>
              <option value="0">Rascunho</option>
            </select>
          </div>    

           <div class="form-group">
            <input type="submit" name="cadastrar" value="Cadastrar pagina" class="btn btn-success">
            <input type="reset" name="limpar" value="Limpar campos" class="btn btn-primary">
            <a href="{{ route('noticias.index') }}" title="Voltar" class="btn btn-default">Voltar</a>
          </div>

        </form>              
      </div>
    </div>
    <!-- /.box -->
<!-- ./row -->
@endsection


@section('js')
<!-- CK Editor -->
<script src="https://cdn.ckeditor.com/4.5.7/standard/ckeditor.js"></script>
<script src="{{ asset('js/plugins/select2/select2.full.min.js') }}"></script>
$(".select2").select2();

<script>
  $(function () {
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('editor1');
  });
</script>
@endsection

</body>
</html>

resources/views/admin/pages/paginas/edit.blade.php
@extends('admin.template')

@section('css')
  <link rel="stylesheet" href="{{ asset('js/plugins/select2/select2.min.css') }}">
@endsection

@section('title', 'Pagina')
@section('sub-title', 'Editar')

@section('rotas')
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ route('paginas.index') }}"><i class="fa  fa-file-o"></i>  Paginas</a></li>
    <li class="active">Editar Pagina</li>
@endsection

@section('conteudo')
<div class="row">
  <div class="col-md-12">
    <div class="box box-info">
    @include('admin.parts.errors')
      <!-- /.box-header -->
      <div class="box-body pad">
        <form action="{{ route('paginas.update', $noticia->id) }}" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}
          <input name="_method" type="hidden" value="PUT">
          
          <div class="form-group">
            <label>Titulo</label>
            <input type="text" class="form-control" value="{{ $noticia->titulo }}" name="titulo" placeholder="">
            <input type="hidden" class="form-control" name="tipo" value="2">
            <input type="hidden" class="form-control" name="user_id" value="{{Auth::user()->id }}">
          </div>  
          <div class="form-group">              
            <label>Categoria</label>
            <select name="categoria_id" class="form-control select2" style="width: 100%;">
              <option selected="selected">Selecione a Categoria </option>
              @foreach($categorias as $c)
                @if( $noticia->categoria_id == $c->id )       
                  <option value="{{ $c->id }}" selected="selected">{{ $c->nome }}</option>
                @else       
                  <option value="{{ $c->id }}">{{ $c->nome }}</option>
                @endif
              @endforeach
            </select>
          </div>

          <div class="form-group">
            <label>Conteudo</label>
            <textarea id="editor1"  name="conteudo" rows="10" cols="80">{{ $noticia->conteudo }}</textarea>
          </div>

          <div class="form-group">              
            <label>Status</label>
            <select name="ativo" class="form-control select2" style="width: 100%;">
              <option value="1" 
              @if($noticia->ativo == 1) 
                selected="selected" 
              @endif >Publicar</option>
              <option value="0" 
              @if($noticia->ativo == 0) 
                selected="selected" 
              @endif
              >Rascunho</option>
            </select>
          </div>    

           <div class="form-group">
            <input type="submit" name="cadastrar" value="Editar Pagina" class="btn btn-success">

            <a href="{{ route('paginas.destroy', $noticia->id) }}" title="Remover Pagina" class="btn btn-danger"  data-method="delete" data-token="{{csrf_token() }}" data-confirm="Você tem certeza que deseja remover a noticia?">Remover Pagina</a>

            <a href="{{ route('paginas.index') }}" title="Voltar" class="btn btn-default">Voltar</a>
          </div>

        </form>              
      </div>
    </div>
    <!-- /.box -->
<!-- ./row -->
@endsection


@section('js')
<!-- CK Editor -->
<script src="https://cdn.ckeditor.com/4.5.7/standard/ckeditor.js"></script>
<script src="{{ asset('js/plugins/select2/select2.full.min.js') }}"></script>

<script>
  $(function () {
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('editor1');
  });
</script>
@endsection

</body>
</html>

resources/views/admin/pages/paginas/list.blade.php
@extends('admin.template')

@section('css')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('js/plugins/datatables/dataTables.bootstrap.css') }}">
@endsection

@section('title', 'Paginas')
@section('sub-title', 'Todas')

@section('rotas')
  <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
  <li class="active">Paginas</li>
@endsection

@section('conteudo')
   <div class="box">
      <div class="box-header">
        <a href="{{ route('paginas.create') }}" class="btn btn-block btn-primary btn-lg">
          Adicionar uma nova pagina
        </a>        
      </div>      
        <!-- /.box-header -->
        <div class="box-body">
        @include('admin.parts.success')
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>#</th>
                  <th>Nome</th>
                  <th>Categorias</th>
                  <th>Status</th>
                  <th>Data Cadastro</th>
                  <th>Ações</th>
                </tr>
                </thead>
                <tbody>
                @foreach($noticias as $n)
                  <tr>
                    <td>{{ $n->id }}</td>
                    <td>{{ $n->titulo}}</td>
                    <td>{{ $n->categoria->nome  }}</td>
                    <td>@if($n->ativo == 1) Publicado @else Rascunho @endif</td>
                    <td>{{ $n->created_at->format('d/m/Y') }}</td>
                    <td>
                      <a href="{{ route('paginas.edit', $n->id) }}" title="Editar Pagina" class="btn-sm btn-primary"><i class="fa fa-edit"></i></a>
                      @if($n->categoria_id != 4)
                      <a href="{{ route('paginas.destroy', $n->id) }}" title="Remover Pagina" class="btn-sm btn-danger"  data-method="delete" data-token="{{csrf_token() }}" data-confirm="Você tem certeza que deseja remover a noticia?">
                      <i class="fa fa-remove"></i>
                      </a>
                      @endif

                    </td>
                  </tr>    
                @endforeach          
                </tbody>
                <tfoot>
                  <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Categorias</th>
                    <th>Status</th>
                    <th>Data Cadastro</th>
                    <th>Ações</th>
                  </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
@endsection
      
@section('js')

<!-- DataTables -->
<script src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<!-- SlimScroll -->
<script src="{{ asset('js/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('js/plugins/fastclick/fastclick.js') }}"></script>
<!-- AdminLTE App -->

<script>
  $(function () {
    $("#example1").DataTable( {
      "language" :{
        "sEmptyTable": "Nenhum registro encontrado",
        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
        "sInfoPostFix": "",
        "sInfoThousands": ".",
        "sLengthMenu": "_MENU_ resultados por página",
        "sLoadingRecords": "Carregando...",
        "sProcessing": "Processando...",
        "sZeroRecords": "Nenhum registro encontrado",
        "sSearch": "Pesquisar",
        "oPaginate": {
            "sNext": "Próximo",
            "sPrevious": "Anterior",
            "sFirst": "Primeiro",
            "sLast": "Último"
        },
        "oAria": {
            "sSortAscending": ": Ordenar colunas de forma ascendente",
            "sSortDescending": ": Ordenar colunas de forma descendente"
        }
      }
    });    
  });
</script>

@endsection