routes/web.php
<?php

Route::get('login', 'Auth\LoginController@getLogin')->name('login');
Route::post('admin', 'Auth\LoginController@postLogin')->name('login.post');

Route::get('/', 'HomeController@index')->name('site.inicio');

Route::get('liturgia/{dia}/{mes}/{ano}', 'lirtugiaController@index')->name('api.liturgia');

Route::get('liturgia-diaria/{dia}/{mes}/{ano}', 'lirtugiaController@lirtugiaPage')->name('site.lirtugia');

Route::get('pedido-oracao', 'PedidoOracaoController@create')->name('pedido.oracao.index');
Route::post('pedido-oracao', 'PedidoOracaoController@store')->name('pedido.oracao.store');

Route::get('velas', 'PedidoOracaoController@acendaVela')->name('pedido.velas.index');
Route::post('velas', 'PedidoOracaoController@storeVela')->name('pedido.velas.store');


Route::get('pagina/{titulo}/{id}', 'PaginaController@show')->name('site.pagina.show')->where("id", "[0-9]+");

Route::get('noticia/{titulo}/{id}', 'PaginaController@show')->name('site.noticia.show')->where("id", "[0-9]+");

Route::get('noticias', 'NoticiaController@getAllNoticias')->name('site.noticia.all');

Route::get('artigos', 'NoticiaController@getAllArtigos')->name('site.artigo.all');

Route::get('oracoes', 'NoticiaController@getAllOracoes')->name('site.oracao.all');

Route::get('galerias-fotos', 'GaleriaController@getAllGalerias')->name('site.galerias.all');

Route::get('comunidades', 'PaginaController@getAllComunidades')->name('site.comunidade.all');

Route::get('galeria-fotos/{titulo}/{id}', 'GaleriaController@getShow')->name('site.galeria.show');


/**
 * ADMINISTRATIVO
 */
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function() {

	Route::get('deslogar', 'Auth\LoginController@logout')->name('login.deslogar');

	/** Categorias **/
	Route::resource('categorias', 'CategoriaController');

	/** Noticias **/
	Route::resource('noticias', 'NoticiaController');

	/** Paginas **/
	Route::resource('paginas', 'PaginaController');

	/** Galeria **/
	Route::resource('galerias', 'GaleriaController');

	/*** Lirtugia *****/
	Route::resource('lirtugia', 'lirtugiaController');

	Route::get('fotos/{id}', 'GaleriaController@getFotos')->name('fotos.index');
	Route::post('fotos/{id}', 'GaleriaController@postFotos')->name('fotos.store');
	Route::delete('fotos/{id}', 'GaleriaController@deleteFoto')->name('fotos.delete');

	/** Pedidos Oração **/
	Route::resource('pedidos-oracao', 'PedidoOracaoController');

	Route::resource('usuarios', 'UsuarioController');

	Route::get('velas','PedidoOracaoController@getAllVelasAdmin')->name('admin.velas.index');
	Route::get('velas/{id}','PedidoOracaoController@getShowVelasAdmin')->name('admin.velas.show');
	Route::get('velas/{status}/{id}','PedidoOracaoController@getMudarStatus')->name('admin.velas.status');
	Route::delete('velas/{id}','PedidoOracaoController@velaDestroy')->name('admin.velas.destroy');

	Route::get('/', function () {
	    return view('admin/pages/index');
	})->name('home');

});
	

app/Models/PedidoOracao.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PedidoOracao extends Model
{
	protected $table = 'pedido_oracoes';

	protected $fillable = [
		'id',
		'nome',
		'email',
		'telefone',
		'mensagem',
		'status'
	];
}

app/Http/Controllers/PedidoOracaoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\PedidoOracao;
use App\Models\Vela;

class PedidoOracaoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pedidos = PedidoOracao::all();
        return view('admin/pages/pedidooracao/list', compact('pedidos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('site.pages.pedidooracao');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nome' => 'required',
            'email' => 'required|email',
            'mensagem' => 'required|min:10',
            'telefone' => 'required|numeric'
        ]);

        if(PedidoOracao::create($request->all())) {
            
            $request->session()->flash('success', 'Seu Pedido de oração foi enviado com sucesso');

            return redirect()->route('pedido.oracao.index');

        }
        return redirect()->back()->withInput()->withErrors('Erro ao adicionar a categoria!');
    }

        /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $pedido = PedidoOracao::find($id);

        $dados = [
            'status' => 1
        ];
        $pedido->update($dados);

        return view('admin/pages/pedidooracao/show', compact('pedido'));
    }

     /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(PedidoOracao::find($id)->delete()){
            session()->flash('success', 'O pedido de oração foi removida com sucesso');
            return redirect()->route('pedidos-oracao.index');
        }
        return redirect()->back()->withInput()->withErrors('Erro ao remover o pedido de oração!');
    }

    /**
     * VELAS ACENDENDO
     */


    /**
     * 
     */
    public function getAllVelasAdmin()
    {
        $velas = Vela::all();
        return view('admin/pages/vela/list', compact('velas'));
    }

    /**
     * 
     */
    public function getShowVelasAdmin($id)
    {
        $vela = Vela::find($id);
        return view('admin/pages/vela/show', compact('vela'));
    }

    /**
     * 
     */
    public function getMudarStatus($status, $id)
    {
        $dados['status'] = 1;

        $vela = Vela::find($id)->update($dados);
        session()->flash('success', 'A vela foi acesa! Agora ela está disponivel no site.');
        return redirect()->route('admin.velas.index');
    }

    /**
     * 
     */
    public function acendaVela()
    {
        $velas = Vela::where('status', 1)->paginate(9);
        return view('site.pages.acendavela', compact('velas'));
    }

    /**
     * 
     */
    public function storeVela(Request $request)
    {
        $this->validate($request, [
            'nome' => 'required',
            'email' => 'required|email',
            'intencao' => 'required|min:10',
        ]);

        if($request['permitir'] == null)
            $request['permitir'] = 1;
        else
            $request['permitir'] = 0;

        if(Vela::create($request->all())) {
            
            $request->session()->flash('success', 'Sua vela foi acesa! Ela estará disponível em nosso site assim que analisarmos seus dados.');

            return redirect()->route('pedido.velas.index');

        }
        return redirect()->back()->withInput()->withErrors('Erro ao adicionar!');
    }

    /**
     * 
     */
    public function velaDestroy($id)
    {
        if(Vela::find($id)->delete()){
            session()->flash('success', 'A vela foi removida com sucesso');
            return redirect()->route('admin.velas.index');
        }
        return redirect()->back()->withInput()->withErrors('Erro ao remover a vela!');
    }
}

resources/views/admin/pages/pedidooracao/list.blade.php
@extends('admin.template')

@section('css')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('js/plugins/datatables/dataTables.bootstrap.css') }}">
@endsection

@section('title', 'Pedidos de Orações')
@section('sub-title', 'Todos')

@section('rotas')
  <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Pedidos de orações</li>
@endsection

@section('conteudo')
  <div class="box">
      <div class="box-header">     
      </div>
      
        <!-- /.box-header -->
        <div class="box-body">
        @include('admin.parts.success')
          <table id="example1" data-order='[[ 0, "desc" ]]' class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>#</th>
              <th>Nome</th>
              <th>Telefone</th>
              <th>Email</th>
              <th>Data</th>
              <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            @foreach($pedidos as $c)
            <tr @if($c->status == 0) class="danger" @endif>
              <td>{{ $c->id }}</td>
              <td>{{ $c->nome }}</td>
              <td>{{ $c->telefone }}</td>
              <td>{{ $c->email }}</td>
              <td>{{ date('d/m/Y', strtotime($c->created_at)) }}</td>
              <td class="text-center">
                  <a href="{{ route('pedidos-oracao.show', $c->id) }}" title="Ver pedido de oração" class="btn-sm btn-default" >
                    <i class="fa fa-eye"></i>
                  </a>
                  <a href="{{ route('pedidos-oracao.destroy', $c->id) }}" title="Remover categoria" class="btn-sm btn-danger"  data-method="delete" data-token="{{csrf_token() }}" data-confirm="Você tem certeza que deseja remover esse pedido de oração?">
                    <i class="fa fa-remove"></i>
                  </a>
              </td>
            </tr>
            @endforeach
            </tbody>
            <tfoot>
            <tr>
              <th>#</th>
              <th>Nome</th>
              <th>Telefone</th>
              <th>Email</th>
              <th>Data</th>
              <th>Ações</th>
            </tr>
            </tfoot>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
      <!-- /.row -->
@endsection
      
@section('js')

<!-- DataTables -->
<script src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<!-- SlimScroll -->
<script src="{{ asset('js/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('js/plugins/fastclick/fastclick.js') }}"></script>

<!-- AdminLTE App -->

<script>
  $(function () {
    $("#example1").DataTable( {
      "language" :{
        "sEmptyTable": "Nenhum registro encontrado",
        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
        "sInfoPostFix": "",
        "sInfoThousands": ".",
        "sLengthMenu": "_MENU_ resultados por página",
        "sLoadingRecords": "Carregando...",
        "sProcessing": "Processando...",
        "sZeroRecords": "Nenhum registro encontrado",
        "sSearch": "Pesquisar",
        "oPaginate": {
            "sNext": "Próximo",
            "sPrevious": "Anterior",
            "sFirst": "Primeiro",
            "sLast": "Último"
        },
        "oAria": {
            "sSortAscending": ": Ordenar colunas de forma ascendente",
            "sSortDescending": ": Ordenar colunas de forma descendente"
        }
      },
    });    
  });
</script>

@endsection

resources/views/admin/pages/pedidooracao/show.blade.php
@extends('admin.template')

@section('css')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('js/plugins/datatables/dataTables.bootstrap.css') }}">
@endsection

@section('title', 'Pedidos de Oração')

@section('rotas')
  <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Detalhes do pedido de oração</li>
@endsection

@section('conteudo')
  <div class="box">
      <div class="box-header">
			
      </div>
      
        <!-- /.box-header -->
        <div class="box-body">
        	<p><strong>De:</strong> {{ $pedido->nome }}</p>
        	<p><strong>Telefone:</strong> {{ $pedido->telefone }} </p>
        	<p><strong>E-mail:</strong> {{ $pedido->email }} </p>
        	<p><strong>Mensagem:</strong> {{ $pedido->mensagem }} </p>
          	<a href="{{ route('pedidos-oracao.index') }}" class="btn btn-default"> Voltar </a>
          	<button type="button" class="btn btn-default"><i class="fa fa-print"></i> Imprimir</button>
      <!-- /.box -->
    	</div>
    <!-- /.col -->
  </div>
      <!-- /.row -->
@endsection
      
@section('js')

<!-- DataTables -->
<script src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<!-- SlimScroll -->
<script src="{{ asset('js/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('js/plugins/fastclick/fastclick.js') }}"></script>

<!-- AdminLTE App -->
@endsection