routes/web.php
<?php

Route::get('login', 'Auth\LoginController@getLogin')->name('login');
Route::post('admin', 'Auth\LoginController@postLogin')->name('login.post');

Route::get('/', 'HomeController@index')->name('site.inicio');

Route::get('liturgia/{dia}/{mes}/{ano}', 'lirtugiaController@index')->name('api.liturgia');

Route::get('liturgia-diaria/{dia}/{mes}/{ano}', 'lirtugiaController@lirtugiaPage')->name('site.lirtugia');

Route::get('pedido-oracao', 'PedidoOracaoController@create')->name('pedido.oracao.index');
Route::post('pedido-oracao', 'PedidoOracaoController@store')->name('pedido.oracao.store');

Route::get('velas', 'PedidoOracaoController@acendaVela')->name('pedido.velas.index');
Route::post('velas', 'PedidoOracaoController@storeVela')->name('pedido.velas.store');


Route::get('pagina/{titulo}/{id}', 'PaginaController@show')->name('site.pagina.show')->where("id", "[0-9]+");

Route::get('noticia/{titulo}/{id}', 'PaginaController@show')->name('site.noticia.show')->where("id", "[0-9]+");

Route::get('noticias', 'NoticiaController@getAllNoticias')->name('site.noticia.all');

Route::get('artigos', 'NoticiaController@getAllArtigos')->name('site.artigo.all');

Route::get('oracoes', 'NoticiaController@getAllOracoes')->name('site.oracao.all');

Route::get('galerias-fotos', 'GaleriaController@getAllGalerias')->name('site.galerias.all');

Route::get('comunidades', 'PaginaController@getAllComunidades')->name('site.comunidade.all');

Route::get('galeria-fotos/{titulo}/{id}', 'GaleriaController@getShow')->name('site.galeria.show');


/**
 * ADMINISTRATIVO
 */
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function() {

	Route::get('deslogar', 'Auth\LoginController@logout')->name('login.deslogar');

	/** Categorias **/
	Route::resource('categorias', 'CategoriaController');

	/** Noticias **/
	Route::resource('noticias', 'NoticiaController');

	/** Paginas **/
	Route::resource('paginas', 'PaginaController');

	/** Galeria **/
	Route::resource('galerias', 'GaleriaController');

	/*** Lirtugia *****/
	Route::resource('lirtugia', 'lirtugiaController');

	Route::get('fotos/{id}', 'GaleriaController@getFotos')->name('fotos.index');
	Route::post('fotos/{id}', 'GaleriaController@postFotos')->name('fotos.store');
	Route::delete('fotos/{id}', 'GaleriaController@deleteFoto')->name('fotos.delete');

	/** Pedidos Oração **/
	Route::resource('pedidos-oracao', 'PedidoOracaoController');

	Route::resource('usuarios', 'UsuarioController');

	Route::get('velas','PedidoOracaoController@getAllVelasAdmin')->name('admin.velas.index');
	Route::get('velas/{id}','PedidoOracaoController@getShowVelasAdmin')->name('admin.velas.show');
	Route::get('velas/{status}/{id}','PedidoOracaoController@getMudarStatus')->name('admin.velas.status');
	Route::delete('velas/{id}','PedidoOracaoController@velaDestroy')->name('admin.velas.destroy');

	Route::get('/', function () {
	    return view('admin/pages/index');
	})->name('home');

});
	

app/Models/Galeria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Galeria extends Model
{
    protected $fillable = [
    	'id',
        'nome',
        'descricao',
        'ativo',
        'user_id'
    ];


    public function fotos() 
    {
    	return $this->hasMany(Foto::class);
    }

}

app/Http/Controllers/GaleriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Galeria;
use App\Models\Foto;
use Image;

class GaleriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $galerias = Galeria::all();
        return view('admin/pages/galerias/list', compact('galerias'));
    }


    /** Page de todos as galerias de fotos **/
    public function getAllGalerias()
    {
        $galerias = Galeria::where('ativo', 1)->paginate(6);
        return view('site.pages.galeriasFotos', compact('galerias'));
    }

    public function getShow($titulo, $id)
    {
         $galeria = Galeria::find($id);
         return view('site.pages.galeria', compact('galeria'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/pages/galerias/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nome' => 'required|unique:galerias,nome',
            'descricao' => 'required',
            'ativo' => 'required'
        ]);

        if(Galeria::create($request->all())) {
            $request->session()->flash('success', 'A galeria foi adicionada com sucesso');
            return redirect()->route('galerias.index');
        }

        return redirect()->back()
            ->withInput()
            ->withErrors('Erro ao adicionar a noticia!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $galeria = Galeria::find($id);
        return view('admin/pages/galerias/edit', compact('galeria'));
    }

    /**
     * Todas as fotos 
     */
    public function getFotos($id) 
    {
        $galeria = Galeria::find($id);
        $fotos =  Foto::where('galeria_id', $id)->orderBy('created_at', 'desc')->get();
        return view('admin/pages/fotos/list', compact('fotos', 'galeria'));
    }


    /**
     * 
     */
    public function postFotos(Request $request, $id) 
    {
        $image = $request->file('file');
        $filename  = time().'-'.uniqid().'.'.$image->getClientOriginalExtension();        
        $pathGrande = public_path('uploads/galerias/grande/'.$filename);
        $pathPequena = public_path('uploads/galerias/pequena/'.$filename);
        
        if(Image::make($image->getRealPath())->resize(600, 600,
            function ($constraint) {
                $constraint->aspectRatio();
            }
        )->save($pathGrande)) {
            Image::make($image->getRealPath())->resize(250, 250, 
                function ($constraint) {
                    $constraint->aspectRatio();
                }
            )->save($pathPequena);

            $request['galeria_id'] = $id;
            $request['nome'] = $filename;

            Foto::create($request->all());
        }
        $request->session()->flash('success', 'As fotos foram adicionadas com sucesso!');
        return response()->json('sucesso', 200);       
    }

    /**
     * 
     */
    public function deleteFoto($id)
    {
        $delete = Foto::find($id);        
        if($delete->delete()){
            unlink(public_path('uploads/galerias/grande/').$delete->nome);
            unlink(public_path('uploads/galerias/pequena/').$delete->nome);

            session()->flash('success', 'A foto foi removida com sucesso');
            return redirect()->back();
        }
        return redirect()->back()->withInput()->withErrors('Erro ao remover a foto!');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nome' => 'required|unique:galerias,nome,'.$id,
            'descricao' => 'required',
            'ativo' => 'required'
        ]);

        if(Galeria::find($id)->update($request->all())) {
            $request->session()->flash('success', 'A galeria foi atualizada com sucesso');
            return redirect()->route('galerias.index');
        }

        return redirect()->back()
            ->withInput()
            ->withErrors('Erro ao atualizar a galeria!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/pages/galerias/create.blade.php
@extends('admin.template')

@section('css')

@endsection

@section('title', 'Galeria')
@section('sub-title', 'Nova')

@section('rotas')
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="{{ route('galerias.index') }}"><i class="fa fa-file-photo-o"></i> Galerias</a></li>
    <li class="active">Nova Galeria</li>
@endsection

@section('conteudo')
<div class="row">
  <div class="col-md-12">
    <div class="box box-info">
      <!-- /.box-header -->
      <div class="box-body pad">
        @include('admin.parts.errors')
        <form action="{{ route('galerias.store') }}"  method="post"  enctype="multipart/form-data">
          {{ csrf_field() }}
          <div class="form-group">
            <label>Nome</label>
            <input type="text" name="nome" class="form-control" value="{{ old('nome') }}" placeholder="Nome da Galeria">
            <input type="hidden" class="form-control" name="user_id" value="{{Auth::user()->id }}">
          </div>
          <div class="form-group">
            <label>Descrição</label>
            <textarea id="editor1" name="descricao" rows="5" cols="80"></textarea>
          </div>
          <div class="form-group">              
            <label>Status</label>
            <select name="ativo" class="form-control select2" style="width: 100%;">
              <option value="1" selected="selected">Publicar</option>
              <option value="0">Rascunho</option>
            </select>
          </div>  

          <div class="form-group">
            <input type="submit" name="cadastrar" value="Cadastrar Galeria" class="btn btn-success">
            <input type="reset" name="limpar" value="Limpar campos" class="btn btn-primary">
            <a href="{{ route('galerias.index') }}" title="Voltar" class="btn btn-default">Voltar</a>
          </div>
        </form>
              
      </div>
    </div>
    <!-- /.box -->
<!-- ./row -->
@endsection


@section('js')
<!-- CK Editor -->
<script src="https://cdn.ckeditor.com/4.5.7/standard/ckeditor.js"></script>

<script>
  $(function () {
    CKEDITOR.replace('editor1');
  });
</script>
@endsection

</body>
</html>

resources/views/admin/pages/galerias/edit.blade.php
@extends('admin.template')

@section('css')

@endsection

@section('title', 'Galeria')
@section('sub-title', 'Editar')

@section('rotas')
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="{{ route('galerias.index') }}"><i class="fa fa-file-photo-o"></i> Galerias</a></li>
    <li class="active">Editar Galeria</li>
@endsection

@section('conteudo')
<div class="row">
  <div class="col-md-12">
    <div class="box box-info">
      <!-- /.box-header -->
      <div class="box-body pad">
        @include('admin.parts.errors')
        <form action="{{ route('galerias.update', $galeria->id) }}"  method="post">
          {{ csrf_field() }}
          <input name="_method" type="hidden" value="PUT">
          <div class="form-group">
            <label>Nome</label>
            <input type="text" name="nome" class="form-control" value="{{ $galeria->nome }}" placeholder="Nome da Galeria">
            <input type="hidden" class="form-control" name="user_id" value="{{Auth::user()->id }}">
          </div>
          <div class="form-group">
            <label>Descrição</label>
            <textarea id="editor1" name="descricao" rows="5" cols="80">{{ $galeria->descricao }}</textarea>
          </div>
          <div class="form-group">              
            <label>Status</label>
            <select name="ativo" class="form-control select2" style="width: 100%;">
              <option value="1" selected="selected">Publicar</option>
              <option value="0">Rascunho</option>
            </select>
          </div>  

          <div class="form-group">
            <input type="submit" name="cadastrar" value="Atualizar Galeria" class="btn btn-success">
             <a href="{{ route('galerias.destroy', $galeria->id) }}" title="Remover Noticia" class="btn btn-danger"  data-method="delete" data-token="{{csrf_token() }}" data-confirm="Você tem certeza que deseja remover essa galeria?">Remover Galeria</a>
            <a href="{{ route('galerias.index') }}" title="Voltar" class="btn btn-default">Voltar</a>
          </div>
        </form>
              
      </div>
    </div>
    <!-- /.box -->
<!-- ./row -->
@endsection


@section('js')
<!-- CK Editor -->
<script src="https://cdn.ckeditor.com/4.5.7/standard/ckeditor.js"></script>

<script>
  $(function () {
    CKEDITOR.replace('editor1');
  });
</script>
@endsection

</body>
</html>

resources/views/admin/pages/galerias/list.blade.php
@extends('admin.template')

@section('css')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('js/plugins/datatables/dataTables.bootstrap.css') }}">
@endsection

@section('title', 'Galerias')
@section('sub-title', 'Todas')

@section('rotas')
  <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Galerias</li>
@endsection

@section('conteudo')
  <div class="box">
      <div class="box-header">
        <a href="{{ route('galerias.create') }}" class="btn btn-block btn-primary btn-lg">
          Adicionar uma nova galeria
        </a>        
      </div>
      
        <!-- /.box-header -->
        <div class="box-body">
        @include('admin.parts.success')
          <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>#</th>
              <th>Nome</th>
              <th>Status</th>
              <th>Qtd Fotos</th>
              <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            @foreach($galerias as $c)
            <tr>
              <td>{{ $c->id }}</td>
              <td>{{ $c->nome }}</td>
              <td>@if($c->ativo == 1) Publicado @else Rascunho @endif</td>
              <td>{{ count($c->fotos) }}</td>
              <td class="text-center">
                  <a href="{{ route('fotos.index', $c->id) }}" title="Adicionar/Remover Fotos" class="btn-sm btn-success"><i class="fa fa-plus"></i></a>

                  <a href="{{ route('galerias.edit', $c->id) }}" title="Editar galeria" class="btn-sm btn-primary"><i class="fa fa-edit"></i></a>       

                  <a href="{{ route('galerias.destroy', $c->id) }}" title="Remover Galeria" class="btn-sm btn-danger"  data-method="delete" data-token="{{csrf_token() }}" data-confirm="Você tem certeza que deseja remover essa galeria?">
                    <i class="fa fa-remove"></i>
                  </a>
              </td>
            </tr>
            @endforeach
            </tbody>
            <tfoot>
            <tr>
              <th>#</th>
              <th>Nome</th>
              <th>Status</th>
              <th>Qtd Fotos</th>
              <th>Ações</th>
            </tr>
            </tfoot>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
      <!-- /.row -->
@endsection
      
@section('js')

<!-- DataTables -->
<script src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<!-- SlimScroll -->
<script src="{{ asset('js/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('js/plugins/fastclick/fastclick.js') }}"></script>
<!-- AdminLTE App -->

<script>
  $(function () {
    $("#example1").DataTable( {
      "language" :{
        "sEmptyTable": "Nenhum registro encontrado",
        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
        "sInfoPostFix": "",
        "sInfoThousands": ".",
        "sLengthMenu": "_MENU_ resultados por página",
        "sLoadingRecords": "Carregando...",
        "sProcessing": "Processando...",
        "sZeroRecords": "Nenhum registro encontrado",
        "sSearch": "Pesquisar",
        "oPaginate": {
            "sNext": "Próximo",
            "sPrevious": "Anterior",
            "sFirst": "Primeiro",
            "sLast": "Último"
        },
        "oAria": {
            "sSortAscending": ": Ordenar colunas de forma ascendente",
            "sSortDescending": ": Ordenar colunas de forma descendente"
        }
      },
    });    
  });
</script>

@endsection